Declare @PartnerId varchar(30) = null;

delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'en-US' and FieldName = 'lnxbtnDutyADDExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'en-US', 'lnxbtnDutyADDExtract', N'Export to Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'en-US' and FieldName = 'lnxbtnDutyMainExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'en-US', 'lnxbtnDutyMainExtract', N'Export to Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'en-US' and FieldName = 'lnxbtnDutyPrefExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'en-US', 'lnxbtnDutyPrefExtract', N'Export to Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'en-US' and FieldName = 'lnxbtnOtherChargesVATExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'en-US', 'lnxbtnOtherChargesVATExtract', N'Export to Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'en-US' and FieldName = 'lnxbtnOtherExportChargesExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'en-US', 'lnxbtnOtherExportChargesExtract', N'Export to Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 

delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'es-MX' and FieldName = 'lbxFutureDateMessage' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'es-MX', 'lbxFutureDateMessage', N'Debido al dinamismo de las Tarifas Arancelarias, la información futura mostrada abajo se proporciona sólo como referencia.', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'es-MX' and FieldName = 'lbxFutureDateMessage' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'es-MX', 'lbxFutureDateMessage', N'Debido al dinamismo de las Tarifas Arancelarias, la información futura mostrada abajo se proporciona sólo como referencia.', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'es-MX' and FieldName = 'lbxFutureDateMessage' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'es-MX', 'lbxFutureDateMessage', N'Debido al dinamismo de las Tarifas Arancelarias, la información futura mostrada abajo se proporciona sólo como referencia.', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'es-MX' and FieldName = 'lbxFutureDateMessage' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'es-MX', 'lbxFutureDateMessage', N'Debido al dinamismo de las Tarifas Arancelarias, la información futura mostrada abajo se proporciona sólo como referencia.', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'es-MX' and FieldName = 'lbxFutureDateMessage' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'es-MX', 'lbxFutureDateMessage', N'Debido al dinamismo de las Tarifas Arancelarias, la información futura mostrada abajo se proporciona sólo como referencia.', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 

delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'fr-FR' and FieldName = 'lnxbtnDutyADDExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'fr-FR', 'lnxbtnDutyADDExtract', N'Exporter au format Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'fr-FR' and FieldName = 'lnxbtnDutyMainExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'fr-FR', 'lnxbtnDutyMainExtract', N'Exporter au format Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'fr-FR' and FieldName = 'lnxbtnDutyPrefExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'fr-FR', 'lnxbtnDutyPrefExtract', N'Exporter au format Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'fr-FR' and FieldName = 'lnxbtnOtherChargesVATExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'fr-FR', 'lnxbtnOtherChargesVATExtract', N'Exporter au format Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'fr-FR' and FieldName = 'lnxbtnOtherExportChargesExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'fr-FR', 'lnxbtnOtherExportChargesExtract', N'Exporter au format Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 

delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'pt-PT' and FieldName = 'lnxbtnDutyADDExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'pt-PT', 'lnxbtnDutyADDExtract', N'Exportar para Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'pt-PT' and FieldName = 'lnxbtnDutyMainExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'pt-PT', 'lnxbtnDutyMainExtract', N'Exportar para Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'pt-PT' and FieldName = 'lnxbtnDutyPrefExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'pt-PT', 'lnxbtnDutyPrefExtract', N'Exportar para Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'pt-PT' and FieldName = 'lnxbtnOtherChargesVATExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'pt-PT', 'lnxbtnOtherChargesVATExtract', N'Exportar para Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
delete from tmgPartnerCultureDefinitions  Where (PartnerId = @PartnerId Or @PartnerId Is Null) and CultureGuid = 'pt-PT' and FieldName = 'lnxbtnOtherExportChargesExtract' insert into tmgPartnerCultureDefinitions  select PartnerId, getDate(), 'pt-PT', 'lnxbtnOtherExportChargesExtract', N'Exportar para Excel', 'N', 'N' From tmgPartnerDataConnection (nolock) Where (PartnerId = @PartnerId Or @PartnerId Is Null) 
