# # .NET Desktop
# # Build and run tests for .NET Desktop or Windows classic desktop solutions.
# # Add steps that publish symbols, save build artifacts, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net



pool:
  vmImage: 'windows-latest'


variables:
  - group: partnerid-variables-test


jobs:
- job: GetpartneridsJob
  steps:
  - task: PowerShell@2
    name: PartneridStask
    displayName: 'Configure variables to be used throughout the build pipeline (this yaml script).'
    inputs:
      targetType: 'filePath'    
      filePath: 'Database/aws-partner-create-test-test.ps1'
      arguments: -server $(sql.server)
      errorActionPreference: 'stop'
- template: azure-pipelines-loops.yml
parameters:
- name: key
  type: object
  default: [ ]
    - one
    - two
  # - name: buildSteps # the name of the parameter is buildSteps
  #   type: object # data type is StepList
  #   default: [$(partnerid)] # default value of buildSteps
