# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)


pool:
  vmImage: 'windows-latest'


variables:
  - group: partnerid-variables-test


jobs:
- job: getpartneridsjob
  steps:
  - task: PowerShell@2
    name: partneridstask
    inputs:
      targetType: 'filePath'    
      filePath: 'Database/aws-partner-create-test-test.ps1'
      arguments: -server $(sql.server)
      errorActionPreference: 'stop'

- job: partnerdb
  displayName: 'partnerdbjob'
  dependsOn: getpartneridsjob
  variables: 
      some: $[ dependencies.getpartneridsjob.outputs['partneridstask.name'] ]
      #some: "hello"


  steps:
  - task: PowerShell@2
    displayName: 'partneridstask'
    inputs:
      targetType: 'filePath'    
      filePath: 'Database/aws-partner-create-test-test-partnerid.ps1'
      arguments: -Veriable $(some)
      errorActionPreference: 'stop'
