IF EXISTS (select * from dbo.sysobjects where id = object_id(N'dbo.txdMXBrokerPedimentoHeader') 
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN	
	PRINT 'Table Already Exists... Skipping'
END
ELSE
BEGIN
	CREATE TABLE [dbo].[txdMXBrokerPedimentoHeader](
		[PartnerID] [int] NOT NULL,
		[EffDate] [datetime] NOT NULL,
		[PedimentoNum] [varchar](30) NOT NULL,
		[PedimentoCategory] [varchar](5) NOT NULL,
		[PedimentoCode] [varchar](5) NOT NULL,
		[PedimentoRegimen] [varchar](5) NOT NULL,
		[DestinationOrigin] [varchar](5) NOT NULL,
		[MXExchangeRate] [numeric](38, 20) NOT NULL,
		[ManifestWeight] [numeric](38, 20) NOT NULL,
		[ManifestWeightUom] [varchar](3) NOT NULL,
		[CustomsImportExportLocation] [varchar](5) NOT NULL,
		[CustomsFilingLocation] [varchar](5) NOT NULL,
		[ArrivalMOT] [varchar](3) NOT NULL,
		[DepartureMOT] [varchar](3) NOT NULL,
		[ImportExportMOT] [varchar](3) NOT NULL,
		[GrossValue] [numeric](38, 20) NOT NULL,
		[GrossValueCurrencyCode] [varchar](3) NOT NULL,
		[MXGrossValue] [numeric](38, 20) NOT NULL,
		[MXGrossValueCurrencyCode] [varchar](3) NOT NULL,
		[MXCommercialValue] [numeric](38, 20) NOT NULL,
		[MXCommercialValueCurrencyCode] [varchar](3) NOT NULL,
		[CompanyName] [varchar](200) NOT NULL,
		[CompanyFederalID] [varchar](20) NOT NULL,
		[CompanyCURP] [varchar](20) NOT NULL,
		[CompanyAddress1] [varchar](200) NOT NULL,
		[CompanyAddress2] [varchar](200) NOT NULL,
		[CompanyCity] [varchar](50) NOT NULL,
		[CompanyState] [varchar](50) NOT NULL,
		[CompanyColony] [varchar](100) NOT NULL,
		[CompanyPostalCode] [varchar](10) NOT NULL,
		[CompanyCountry] [varchar](20) NOT NULL,
		[CompanyRNIMCode] [varchar](20) NOT NULL,
		[InsuranceCharges] [numeric](38, 20) NOT NULL,
		[InsuranceChargesCurrencyCode] [varchar](3) NOT NULL,
		[InsuredValue] [numeric](38, 20) NOT NULL,
		[InsuredValueCurrencyCode] [varchar](3) NOT NULL,
		[FreightCharges] [numeric](38, 20) NOT NULL,
		[FreightChargesCurrencyCode] [varchar](3) NOT NULL,
		[PackingCharges] [numeric](38, 20) NOT NULL,
		[PackingChargesCurrencyCode] [varchar](3) NOT NULL,
		[MiscCharges] [numeric](38, 20) NOT NULL,
		[MiscChargesCurrencyCode] [varchar](3) NOT NULL,
		[AuthorizationCode] [varchar](20) NOT NULL,
		[ClosingAuthorizationCode] [varchar](20) NOT NULL,
		[ManifestQty] [numeric](38, 20) NOT NULL,
		[ManifestQtyUom] [varchar](3) NOT NULL,
		[ContainerCount] [numeric](38, 20) NOT NULL,
		[ProcessingFee] [numeric](38, 20) NOT NULL,
		[ProcessingFeeCurrencyCode] [varchar](3) NOT NULL,
		[ValidationFee] [numeric](38, 20) NOT NULL,
		[ValidationFeeCurrencyCode] [varchar](3) NOT NULL,
		[ProcessingFeeTotal] [numeric](38, 20) NOT NULL,
		[ValidationFeeTotal] [numeric](38, 20) NOT NULL,
		[InvoiceCount] [numeric](38, 20) NOT NULL,
		[TotalVAT] [numeric](38, 20) NOT NULL,
		[TotalDutiesCash] [numeric](38, 20) NOT NULL,
		[TotalDutiesOther] [numeric](38, 20) NOT NULL,
		[BrokerCompanyID] [int] NOT NULL,
		[BrokerName] [varchar](100) NOT NULL,
		[BrokerFederalID] [varchar](20) NOT NULL,
		[BrokerCURP] [varchar](20) NOT NULL,
		[FileSequenceNum] [int] NOT NULL,
		[PedimentoBeginDate] [datetime] NOT NULL,
		[PedimentoEndDate] [datetime] NOT NULL,
		[PedimentoEnteredDate] [datetime] NOT NULL,
		[PedimentoPaymentDate] [datetime] NOT NULL,
		[LastProcessedDate] [datetime] NOT NULL,
		[SubmissionDate] [datetime] NOT NULL,
		[ElectronicSignatureType] [varchar](3) NOT NULL,
		[ElectronicSignature] [varchar](5000) NOT NULL,
		[ElectronicSignatureCertificateNum] [varchar](50) NOT NULL,
		[ObservationText] [varchar](8000) NOT NULL,
		[DeletedFlag] [varchar](1) NOT NULL,
		[KeepDuringRollback] [varchar](1) NOT NULL,
	 CONSTRAINT [PK_txdMXBrokerPedimentoHeader] PRIMARY KEY CLUSTERED 
	(
		[PartnerID] ASC,
		[PedimentoNum] ASC
	) ON [PRIMARY]
	) ON [PRIMARY]
END


