IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP001TR00003PC' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP001TR00003PC','PPIM','Y','N','N')
IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP002TR00003PC' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP002TR00003PC','PNIM','Y','N','N')
IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP001TR00007IM' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP001TR00007IM','IPIM','Y','N','N')
IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP001TR00007PC' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP001TR00007PC','IPPC','Y','N','N')
IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP002TR00007IM' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP002TR00007IM','INIM','Y','N','N')
IF NOT EXISTS (SELECT 1 FROM tmgGlobalCodes WHERE partnerID = (SELECT TOP 1 PartnerID FROM tmfDefaults) AND FieldName = 'IPAPI_MovementType' AND Code = 'MTP002TR00007PC' )
	INSERT INTO tmgGlobalCodes VALUES((SELECT TOP 1 PartnerID FROM tmfDefaults),GETDATE(),'IPAPI_MovementType','MTP002TR00007PC','INPC','Y','N','N')