PRINT '.........CREATE/MODIFY txdCNDeclarationData.............' 
IF EXISTS (SELECT TOP 1 1 FROM sys.tables
			WHERE Name = 'txdCNDeclarationData' 
			AND Type = 'U')
BEGIN
	
	IF (	
		SELECT COUNT(*) FROM dbo.syscolumns
		WHERE name IN (
		'ClearanceSheetType',
	    'Mode',
		'RltEntryNo'
	
		
           )
			AND ID = OBJECT_ID('txdCNDeclarationData')	
		) = 3
	BEGIN
		PRINT ''
		PRINT 'Column Already Exists... '
		
	END
	ELSE
	BEGIN
		if exists (select TOP 1 1 from sys.tables where Name = 'Tmp_txdCNDeclarationData' 
					AND Type = 'U')
		begin
			DROP TABLE Tmp_txdCNDeclarationData 
		end
		
		
		CREATE TABLE [dbo].[Tmp_txdCNDeclarationData]   
		(
			[PartnerId] [int] NOT NULL,
	[EffDate] [datetime] NOT NULL,
	[DeclarationGUID] [varchar](50) NOT NULL,
	[DeclarationDataGUID] [varchar](50) NOT NULL,
	[SequenceNum] [int] NOT NULL,
	[SeqNo] [nvarchar](18) NOT NULL,
	[IEFlag] [nvarchar](255) NOT NULL,
	[Type] [nvarchar](255) NOT NULL,
	[AgentCode] [nvarchar](18) NOT NULL,
	[AgentName] [nvarchar](512) NOT NULL,
	[ApprNo] [nvarchar](32) NOT NULL,
	[BillNo] [nvarchar](32) NOT NULL,
	[ContrNo] [nvarchar](32) NOT NULL,
	[CustomMaster] [nvarchar](255) NOT NULL,
	[CutMode] [nvarchar](255) NOT NULL,
	[DistinatePort] [nvarchar](255) NOT NULL,
	[FeeCurr] [nvarchar](255) NOT NULL,
	[FeeMark] [nvarchar](255) NOT NULL,
	[FeeRate] [numeric](19, 5) NOT NULL,
	[GrossWet] [numeric](19, 5) NOT NULL,
	[IEDate] [datetime] NULL,
	[IEPort] [nvarchar](255) NOT NULL,
	[InsurCurr] [nvarchar](255) NOT NULL,
	[InsurMark] [nvarchar](255) NOT NULL,
	[InsurRate] [numeric](19, 5) NOT NULL,
	[LicenseNo] [nvarchar](20) NOT NULL,
	[ManualNo] [nvarchar](12) NOT NULL,
	[NetWt] [numeric](19, 5) NOT NULL,
	[NoteS] [nvarchar](255) NOT NULL,
	[OtherCurr] [nvarchar](255) NOT NULL,
	[OtherMark] [nvarchar](255) NOT NULL,
	[OtherRate] [numeric](19, 5) NOT NULL,
	[OwnerCode] [nvarchar](18) NOT NULL,
	[OwnerName] [nvarchar](70) NOT NULL,
	[PackNo] [numeric](19, 0) NOT NULL,
	[TradeCode] [nvarchar](18) NOT NULL,
	[TradeCountry] [nvarchar](3) NOT NULL,
	[TradeMode] [nvarchar](6) NOT NULL,
	[TradeName] [nvarchar](512) NOT NULL,
	[TrafMode] [nvarchar](6) NOT NULL,
	[TrafName] [nvarchar](26) NOT NULL,
	[TransMode] [nvarchar](1) NOT NULL,
	[WrapType] [nvarchar](2) NULL,
	[EntryId] [nvarchar](255) NOT NULL,
	[PreEntryId] [nvarchar](36) NOT NULL,
	[EdiId] [nvarchar](255) NOT NULL,
	[Risk] [nvarchar](10) NOT NULL,
	[CopName] [nvarchar](70) NOT NULL,
	[CopCode] [nvarchar](9) NOT NULL,
	[EntryType] [nvarchar](255) NOT NULL,
	[PDate] [datetime] NULL,
	[TypistNo] [nvarchar](30) NOT NULL,
	[InputerName] [nvarchar](32) NOT NULL,
	[PartenerID] [nvarchar](20) NOT NULL,
	[TgdNo] [nvarchar](255) NOT NULL,
	[DataSource] [nvarchar](5) NOT NULL,
	[DeclTrnRel] [nvarchar](1) NOT NULL,
	[ChkSurety] [nvarchar](255) NOT NULL,
	[BillType] [nvarchar](255) NOT NULL,
	[CopCodeScc] [nvarchar](255) NOT NULL,
	[OwnerCodeScc] [nvarchar](255) NOT NULL,
	[AgentCodeScc] [nvarchar](255) NOT NULL,
	[TradeCoScc] [nvarchar](255) NOT NULL,
	[PromiseItmes] [nvarchar](32) NOT NULL,
	[SpecialRelationship] [nvarchar](1) NOT NULL,
	[TransactionValueImpact] [nvarchar](1) NOT NULL,
	[RoyaltyPayment] [nvarchar](1) NOT NULL,
	[SelfDeclarationPayment] [nvarchar](1) NOT NULL,
	[TradeAreaCode] [nvarchar](255) NOT NULL,
	[CheckFlow] [nvarchar](255) NOT NULL,
	[TaxAaminMark] [nvarchar](255) NOT NULL,
	[MarkNo] [nvarchar](400) NOT NULL,
	[DespPortCode] [nvarchar](8) NOT NULL,
	[EntyPortCode] [nvarchar](8) NOT NULL,
	[GoodsPlace] [nvarchar](100) NOT NULL,
	[BLNo] [nvarchar](50) NOT NULL,
	[InspOrgCode] [nvarchar](10) NOT NULL,
	[SpecDeclFlag] [nvarchar](10) NOT NULL,
	[PurpOrgCode] [nvarchar](10) NOT NULL,
	[DespDate] [datetime] NULL,
	[CmplDschrgDt] [nvarchar](8) NOT NULL,
	[CorrelationReasonFlag] [nvarchar](2) NOT NULL,
	[VsaOrgCode] [nvarchar](10) NOT NULL,
	[OrigBoxFlag] [nvarchar](1) NOT NULL,
	[DeclareName] [nvarchar](50) NOT NULL,
	[NoOtherPack] [nvarchar](1) NOT NULL,
	[OrgCode] [nvarchar](10) NOT NULL,
	[OverseasConsignorCode] [nvarchar](50) NOT NULL,
	[OverseasConsignorCname] [nvarchar](150) NOT NULL,
	[OverseasConsignorEname] [nvarchar](100) NOT NULL,
	[OverseasConsignorAddr] [nvarchar](100) NOT NULL,
	[OverseasConsigneeCode] [nvarchar](50) NOT NULL,
	[OverseasConsigneeEname] [nvarchar](400) NOT NULL,
	[DomesticConsigneeEname] [nvarchar](400) NOT NULL,
	[CorrelationNo] [nvarchar](500) NOT NULL,
	[EdiRemark2] [nvarchar](128) NOT NULL,
	[EdiRemark] [nvarchar](128) NOT NULL,
	[RelId] [nvarchar](18) NOT NULL,
	[RelManNo] [nvarchar](255) NOT NULL,
	[BonNo] [nvarchar](32) NOT NULL,
	[VoyNo] [nvarchar](32) NOT NULL,
	[DecBpNo] [nvarchar](32) NOT NULL,
	[CusFie] [nvarchar](8) NOT NULL,
	[DecNo] [nvarchar](13) NOT NULL,
	[DecSignOperType] [nvarchar](255) NOT NULL,
	[DecSignICCode] [nvarchar](255) NOT NULL,
	[DecSignCopCode] [nvarchar](255) NOT NULL,
	[DecSignOperName] [nvarchar](30) NOT NULL,
	[DecSignClientSeqNo] [nvarchar](18) NOT NULL,
	[DecSign] [nvarchar](201) NOT NULL,
	[DecSignDate] [datetime] NULL,
	[DecSignCertificate] [nvarchar](20) NOT NULL,
	[DecSignHostId] [nvarchar](10) NOT NULL,
	[DecSignBillSeqNo] [nvarchar](18) NOT NULL,
	[DecSignDomainId] [nvarchar](255) NOT NULL,
	[DecSignNote] [nvarchar](100) NOT NULL,
	[TrnHeadTrnPreId] [nvarchar](255) NOT NULL,
	[TrnHeadTransNo] [nvarchar](255) NOT NULL,
	[TrnHeadTurnNo] [nvarchar](255) NOT NULL,
	[TrnHeadNativeTrafMode] [nvarchar](255) NOT NULL,
	[TrnHeadTrafCustomsNo] [nvarchar](255) NOT NULL,
	[TrnHeadNativeShipName] [nvarchar](30) NOT NULL,
	[TrnHeadNativeVoyageNo] [nvarchar](255) NOT NULL,
	[TrnHeadContractorName] [nvarchar](70) NOT NULL,
	[TrnHeadContractorCode] [nvarchar](255) NOT NULL,
	[TrnHeadTransFlag] [nvarchar](255) NOT NULL,
	[TrnHeadValidTime] [nvarchar](255) NOT NULL,
	[TrnHeadESealFlag] [nvarchar](255) NOT NULL,
	[TrnHeadNotes] [nvarchar](200) NOT NULL,
	[TrnHeadTrnType] [nvarchar](255) NOT NULL,
	[TrnHeadApplCodeScc] [nvarchar](255) NOT NULL,
	[TrnListTrafMode] [nvarchar](255) NOT NULL,
	[TrnListShipId] [nvarchar](32) NOT NULL,
	[TrnListShipNameEn] [nvarchar](255) NOT NULL,
	[TrnListVoyageNo] [nvarchar](32) NOT NULL,
	[TrnListBillNo] [nvarchar](32) NOT NULL,
	[TrnListIEDate] [datetime] NULL,
	[TaxFileName] [nvarchar](64) NOT NULL,
	[TaxSeqNo] [nvarchar](18) NOT NULL,
	[TaxSddNo] [nvarchar](18) NOT NULL,
	[TaxIEFlag] [nvarchar](255) NOT NULL,
	[TaxDeclPort] [nvarchar](255) NOT NULL,
	[TaxDDate] [datetime] NULL,
	[TaxTradeCo] [nvarchar](255) NOT NULL,
	[TaxTradeName] [nvarchar](70) NOT NULL,
	[TaxInRatio] [nvarchar](255) NOT NULL,
	[TaxTradeMode] [nvarchar](255) NOT NULL,
	[TaxCutMode] [nvarchar](255) NOT NULL,
	[TaxTransMode] [nvarchar](255) NOT NULL,
	[TaxFeeMark] [nvarchar](255) NOT NULL,
	[TaxFeeCurr] [nvarchar](255) NOT NULL,
	[TaxFeeRate] [nvarchar](255) NOT NULL,
	[TaxInsurMark] [nvarchar](255) NOT NULL,
	[TaxInsurCurr] [nvarchar](255) NOT NULL,
	[TaxInsurRate] [nvarchar](255) NOT NULL,
	[TaxOtherMark] [nvarchar](255) NOT NULL,
	[TaxOtherCurr] [nvarchar](255) NOT NULL,
	[TaxOtherRate] [nvarchar](255) NOT NULL,
	[TaxManualNo] [nvarchar](12) NOT NULL,
	[TaxTradeCoScc] [nvarchar](255) NOT NULL,
	[TaxGrossWt] [nvarchar](255) NOT NULL,
	[TaxNoteS] [nvarchar](255) NOT NULL,
	[TaxLegalLiability] [nvarchar](255) NOT NULL,
	[TaxSign] [nvarchar](255) NOT NULL,
	[TaxMessId] [nvarchar](255) NOT NULL,
	[TaxCertSeqNo] [nvarchar](255) NOT NULL,
	[TaxStatus] [nvarchar](255) NOT NULL,
	[TaxFDate] [datetime] NULL,
	[TaxNO] [nvarchar](18) NOT NULL,
	[DecRisk] [nvarchar](10) NOT NULL,
	[DecRiskSign] [nvarchar](201) NOT NULL,
	[DecRiskSignDate] [datetime] NULL,
	[DecRiskNote] [nvarchar](100) NOT NULL,
	[DecSeqNo] [nvarchar](18) NOT NULL,
	[BondInvtNo] [nvarchar](64) NOT NULL,
	[ChgTmsCnt] [numeric](19, 5) NOT NULL,
	[InvtPreentNo] [nvarchar](64) NOT NULL,
	[EtpsInnerInvtNo] [nvarchar](64) NOT NULL,
	[BizopEtpsNo] [nvarchar](10) NOT NULL,
	[RcvgdEtpsNo] [nvarchar](10) NOT NULL,
	[DclEtpsNo] [nvarchar](10) NOT NULL,
	[InvtDclTime] [datetime] NOT NULL,
	[EntryDclTime] [datetime] NOT NULL,
	[RltInvtNo] [nvarchar](64) NOT NULL,
	[RltEntryBizopEtpsScCd] [nvarchar](18) NOT NULL,
	[RltEntryBizopEtpsNo] [nvarchar](10) NOT NULL,
	[RltEntryBizopEtpsNm] [nvarchar](768) NOT NULL,
	[MtpckEndprdMarkCd] [nvarchar](4) NOT NULL,
	[ApplyNo] [nvarchar](64) NOT NULL,
	[DclcusFlag] [nvarchar](1) NOT NULL,
	[DclcusTypeCd] [nvarchar](1) NOT NULL,
	[PrevdTime] [datetime] NOT NULL,
	[FormalVrfdedTime] [datetime] NOT NULL,
	[InvtIoChkPtStuCd] [nvarchar](4) NOT NULL,
	[VrfdedMarkCd] [nvarchar](4) NOT NULL,
	[InvtStuCd] [nvarchar](1) NOT NULL,
	[VrfdedModeCd] [nvarchar](4) NOT NULL,
	[DuCode] [nvarchar](4) NOT NULL,
	[InvtType] [nvarchar](1) NOT NULL,
	[EntryStuCd] [nvarchar](1) NOT NULL,
	[PassportUsedTypeCd] [nvarchar](1) NOT NULL,
	[DclTypeCd] [nvarchar](25) NOT NULL,
	[LevyBlAmt] [numeric](38, 20) NOT NULL,
	[NeedEntryModified] [nvarchar](1) NOT NULL,
	[OptStatus] [nvarchar](10) NOT NULL,
	[CustomName] [nvarchar](50) NOT NULL,
	[ImpexpCustomName] [nvarchar](365) NOT NULL,
	[DclPlcCustomName] [nvarchar](50) NOT NULL,
	[FullTrade] [nvarchar](768) NOT NULL,
	[TrafSpec] [nvarchar](768) NOT NULL,
	[RltEntryRvsngdEtpsScCd] [varchar](18) NOT NULL,
	[RltEntryRcvgdEtpsNo] [varchar](10) NOT NULL,
	[RltEntryRcvgdEtpsNm] [varchar](512) NOT NULL,
	[RltEntryDclEtpsScCd] [varchar](18) NOT NULL,
	[RltEntryDclEtpsNo] [varchar](10) NOT NULL,
	[RltEntryDclEtpsNm] [varchar](512) NOT NULL,
	[ListType] [varchar](1) NOT NULL,
	[InputCode] [varchar](10) NOT NULL,
	[InputName] [varchar](255) NOT NULL,
	[InputTime] [datetime] NOT NULL,
	[ListStat] [varchar](1) NOT NULL,
	[CorrEntryDclEtpsScCd] [varchar](18) NOT NULL,
	[CorrEntryDclEtpsNo] [varchar](10) NOT NULL,
	[CorrEntryDclEtpsNm] [varchar](512) NOT NULL,
	[DecType] [varchar](1) NOT NULL,
	[Param1] [varchar](19) NOT NULL,
	[Param2] [varchar](19) NOT NULL,
	[Param3] [varchar](19) NOT NULL,
	[Param4] [datetime] NOT NULL,
	[DecHeadTradeCiqCode] [nvarchar](10) NOT NULL,
	[DecHeadOwnerCiqCode] [nvarchar](10) NOT NULL,
	[DecHeadDeclCiqCode] [nvarchar](10) NOT NULL,
	[DecRoyaltyFeePricePreDeterminNo] [nvarchar](20) NOT NULL,
	[DecRoyaltyFeeTaxRoyaltyDeclType] [nvarchar](1) NOT NULL,
	[DecRoyaltyFeeContractNo] [nvarchar](500) NOT NULL,
	[DecRoyaltyFeeAuthorizer] [nvarchar](500) NOT NULL,
	[DecRoyaltyFeeAuthorizedPerson] [nvarchar](500) NOT NULL,
	[DecRoyaltyFeePayType] [nvarchar](20) NOT NULL,
	[DecRoyaltyFeePayTime] [datetime] NOT NULL,
	[DecRoyaltyFeePayPeriod] [nvarchar](2) NOT NULL,
	[DecRoyaltyFeeEffectiveDateTime] [datetime] NOT NULL,
	[DecRoyaltyFeeExpirationDateTime] [datetime] NOT NULL,
	[DecRoyaltyFeeRoyaltyAmount] [numeric](19, 5) NOT NULL,
	[DecRoyaltyFeeCurr] [nvarchar](3) NOT NULL,
	[DecRoyaltyFeeRoyaltyFeeType] [nvarchar](5) NOT NULL,
	[DecRoyaltyFeeEdocType] [nvarchar](5) NOT NULL,
	[DecRoyaltyFeeStatment] [nvarchar](2500) NOT NULL,
	[DecRoyaltyFeeIsSecret] [nvarchar](1) NOT NULL,
	[DecRoyaltyFeeIsCusAudit] [nvarchar](1) NOT NULL,
	[DecRoyaltyFeeIsCusPricePreDetermin] [nvarchar](1) NOT NULL,
	[DecRoyaltyFeeIssueDateTime] [datetime] NOT NULL,
	[DecRoyaltyFeePeriodStartDate] [datetime] NOT NULL,
	[DecRoyaltyFeePeriodEndDate] [datetime] NOT NULL,
	[PutrecNo] [nvarchar](64) NOT NULL,
	[BizopEtpsSccd] [nvarchar](18) NOT NULL,
	[BizopEtpsNm] [nvarchar](512) NOT NULL,
	[EntryNo] [nvarchar](64) NOT NULL,
	[RltPutrecNo] [nvarchar](64) NOT NULL,
	[BondInvtTypeCd] [nvarchar](1) NOT NULL,
	[IcCardNo] [nvarchar](20) NOT NULL,
	[Rmk] [nvarchar](4000) NOT NULL,
	[CreateFlag] [nvarchar](1) NOT NULL,
	[ApprovalStatus] [nvarchar](1) NOT NULL,
	[ApprovalDate] [nvarchar](19) NULL,
	[DeclarationDate] [nvarchar](38) NULL,
	[SheetDeclarationTime] [nvarchar](100) NULL,
	[DeclareTime] [nvarchar](100) NULL,
	[Ptr8ApprovalDate] [nvarchar](100) NULL,
	
	
	 --Added
	[ClearanceSheetType] [nvarchar](2) null,
	[Mode] [nvarchar] (2) null,
	
	[RltEntryNo] [nvarchar](64)  NULL,
	[KeepDuringRollback] [varchar](1) NOT NULL,
	[DeletedFlag] [varchar](1) NOT NULL
	
		) ON [PRIMARY]
		

		DECLARE @Before_HasData BIT;
		
		SET @Before_HasData=0

		IF (SELECT TOP 1 1 FROM [txdCNDeclarationData]) = 1 
		BEGIN
			SET @Before_HasData=1
		END
		
		PRINT ''
		PRINT 'INSERT INTO TEMP TABLE......'
		EXEC('INSERT INTO dbo.Tmp_txdCNDeclarationData (
					PartnerId,
	EffDate,
	DeclarationGUID,
	DeclarationDataGUID,
	SequenceNum,
	SeqNo,
	IEFlag,
	Type,
	AgentCode,
	AgentName,
	ApprNo,
	BillNo,
	ContrNo,
	CustomMaster,
	CutMode,
	DistinatePort,
	FeeCurr,
	FeeMark,
	FeeRate,
	GrossWet,
	IEDate,
	IEPort,
	InsurCurr,
	InsurMark,
	InsurRate,
	LicenseNo,
	ManualNo,
	NetWt,
	NoteS,
	OtherCurr,
	OtherMark,
	OtherRate,
	OwnerCode,
	OwnerName,
	PackNo,
	TradeCode,
	TradeCountry,
	TradeMode,
	TradeName,
	TrafMode,
	TrafName,
	TransMode,
	WrapType,
	EntryId,
	PreEntryId,
	EdiId,
	Risk,
	CopName,
	CopCode,
	EntryType,
	PDate,
	TypistNo,
	InputerName,
	PartenerID,
	TgdNo,
	DataSource,
	DeclTrnRel,
	ChkSurety,
	BillType,
	CopCodeScc,
	OwnerCodeScc,
	AgentCodeScc,
	TradeCoScc,
	PromiseItmes,
	SpecialRelationship,
	TransactionValueImpact,
	RoyaltyPayment,
	SelfDeclarationPayment,
	TradeAreaCode,
	CheckFlow,
	TaxAaminMark,
	MarkNo,
	DespPortCode,
	EntyPortCode,
	GoodsPlace,
	BLNo,
	InspOrgCode,
	SpecDeclFlag,
	PurpOrgCode,
	DespDate,
	CmplDschrgDt,
	CorrelationReasonFlag,
	VsaOrgCode,
	OrigBoxFlag,
	DeclareName,
	NoOtherPack,
	OrgCode,
	OverseasConsignorCode,
	OverseasConsignorCname,
	OverseasConsignorEname,
	OverseasConsignorAddr,
	OverseasConsigneeCode,
	OverseasConsigneeEname,
	DomesticConsigneeEname,
	CorrelationNo,
	EdiRemark2,
	EdiRemark,
	RelId,
	RelManNo,
	BonNo,
	VoyNo,
	DecBpNo,
	CusFie,
	DecNo,
	DecSignOperType,
	DecSignICCode,
	DecSignCopCode,
	DecSignOperName,
	DecSignClientSeqNo,
	DecSign,
	DecSignDate,
	DecSignCertificate,
	DecSignHostId,
	DecSignBillSeqNo,
	DecSignDomainId,
	DecSignNote,
	TrnHeadTrnPreId,
	TrnHeadTransNo,
	TrnHeadTurnNo,
	TrnHeadNativeTrafMode,
	TrnHeadTrafCustomsNo,
	TrnHeadNativeShipName,
	TrnHeadNativeVoyageNo,
	TrnHeadContractorName,
	TrnHeadContractorCode,
	TrnHeadTransFlag,
	TrnHeadValidTime,
	TrnHeadESealFlag,
	TrnHeadNotes,
	TrnHeadTrnType,
	TrnHeadApplCodeScc,
	TrnListTrafMode,
	TrnListShipId,
	TrnListShipNameEn,
	TrnListVoyageNo,
	TrnListBillNo,
	TrnListIEDate,
	TaxFileName,
	TaxSeqNo,
	TaxSddNo,
	TaxIEFlag,
	TaxDeclPort,
	TaxDDate,
	TaxTradeCo,
	TaxTradeName,
	TaxInRatio,
	TaxTradeMode,
	TaxCutMode,
	TaxTransMode,
	TaxFeeMark,
	TaxFeeCurr,
	TaxFeeRate,
	TaxInsurMark,
	TaxInsurCurr,
	TaxInsurRate,
	TaxOtherMark,
	TaxOtherCurr,
	TaxOtherRate,
	TaxManualNo,
	TaxTradeCoScc,
	TaxGrossWt,
	TaxNoteS,
	TaxLegalLiability,
	TaxSign,
	TaxMessId,
	TaxCertSeqNo,
	TaxStatus,
	TaxFDate,
	TaxNO,
	DecRisk,
	DecRiskSign,
	DecRiskSignDate,
	DecRiskNote,
	DecSeqNo,
	BondInvtNo,
	ChgTmsCnt,
	InvtPreentNo,
	EtpsInnerInvtNo,
	BizopEtpsNo,
	RcvgdEtpsNo,
	DclEtpsNo,
	InvtDclTime,
	EntryDclTime,
	RltInvtNo,
	RltEntryBizopEtpsScCd,
	RltEntryBizopEtpsNo,
	RltEntryBizopEtpsNm,
	MtpckEndprdMarkCd,
	ApplyNo,
	DclcusFlag,
	DclcusTypeCd,
	PrevdTime,
	FormalVrfdedTime,
	InvtIoChkPtStuCd,
	VrfdedMarkCd,
	InvtStuCd,
	VrfdedModeCd,
	DuCode,
	InvtType,
	EntryStuCd,
	PassportUsedTypeCd,
	DclTypeCd,
	LevyBlAmt,
	NeedEntryModified,
	OptStatus,
	CustomName,
	ImpexpCustomName,
	DclPlcCustomName,
	FullTrade,
	TrafSpec,
	RltEntryRvsngdEtpsScCd,
	RltEntryRcvgdEtpsNo,
	RltEntryRcvgdEtpsNm,
	RltEntryDclEtpsScCd,
	RltEntryDclEtpsNo,
	RltEntryDclEtpsNm,
	ListType,
	InputCode,
	InputName,
	InputTime,
	ListStat,
	CorrEntryDclEtpsScCd,
	CorrEntryDclEtpsNo,
	CorrEntryDclEtpsNm,
	DecType,
	Param1,
	Param2,
	Param3,
	Param4,
	DecHeadTradeCiqCode,
	DecHeadOwnerCiqCode,
	DecHeadDeclCiqCode,
	DecRoyaltyFeePricePreDeterminNo,
	DecRoyaltyFeeTaxRoyaltyDeclType,
	DecRoyaltyFeeContractNo,
	DecRoyaltyFeeAuthorizer,
	DecRoyaltyFeeAuthorizedPerson,
	DecRoyaltyFeePayType,
	DecRoyaltyFeePayTime,
	DecRoyaltyFeePayPeriod,
	DecRoyaltyFeeEffectiveDateTime,
	DecRoyaltyFeeExpirationDateTime,
	DecRoyaltyFeeRoyaltyAmount,
	DecRoyaltyFeeCurr,
	DecRoyaltyFeeRoyaltyFeeType,
	DecRoyaltyFeeEdocType,
	DecRoyaltyFeeStatment,
	DecRoyaltyFeeIsSecret,
	DecRoyaltyFeeIsCusAudit,
	DecRoyaltyFeeIsCusPricePreDetermin,
	DecRoyaltyFeeIssueDateTime,
	DecRoyaltyFeePeriodStartDate,
	DecRoyaltyFeePeriodEndDate,
	PutrecNo,
	BizopEtpsSccd,
	BizopEtpsNm,
	EntryNo,
	RltPutrecNo,
	BondInvtTypeCd,
	IcCardNo,
	Rmk,
	CreateFlag,
	ApprovalStatus,
	ApprovalDate,
	DeclarationDate,
	SheetDeclarationTime,
	DeclareTime,
	Ptr8ApprovalDate,
	ClearanceSheetType,
	Mode,
	RltEntryNo,
	KeepDuringRollback,
	DeletedFlag
	            )
		SELECT 	PartnerId,
	EffDate,
	DeclarationGUID,
	DeclarationDataGUID,
	SequenceNum,
	SeqNo,
	IEFlag,
	Type,
	AgentCode,
	AgentName,
	ApprNo,
	BillNo,
	ContrNo,
	CustomMaster,
	CutMode,
	DistinatePort,
	FeeCurr,
	FeeMark,
	FeeRate,
	GrossWet,
	IEDate,
	IEPort,
	InsurCurr,
	InsurMark,
	InsurRate,
	LicenseNo,
	ManualNo,
	NetWt,
	NoteS,
	OtherCurr,
	OtherMark,
	OtherRate,
	OwnerCode,
	OwnerName,
	PackNo,
	TradeCode,
	TradeCountry,
	TradeMode,
	TradeName,
	TrafMode,
	TrafName,
	TransMode,
	WrapType,
	EntryId,
	PreEntryId,
	EdiId,
	Risk,
	CopName,
	CopCode,
	EntryType,
	PDate,
	TypistNo,
	InputerName,
	PartenerID,
	TgdNo,
	DataSource,
	DeclTrnRel,
	ChkSurety,
	BillType,
	CopCodeScc,
	OwnerCodeScc,
	AgentCodeScc,
	TradeCoScc,
	PromiseItmes,
	SpecialRelationship,
	TransactionValueImpact,
	RoyaltyPayment,
	SelfDeclarationPayment,
	TradeAreaCode,
	CheckFlow,
	TaxAaminMark,
	MarkNo,
	DespPortCode,
	EntyPortCode,
	GoodsPlace,
	BLNo,
	InspOrgCode,
	SpecDeclFlag,
	PurpOrgCode,
	DespDate,
	CmplDschrgDt,
	CorrelationReasonFlag,
	VsaOrgCode,
	OrigBoxFlag,
	DeclareName,
	NoOtherPack,
	OrgCode,
	OverseasConsignorCode,
	OverseasConsignorCname,
	OverseasConsignorEname,
	OverseasConsignorAddr,
	OverseasConsigneeCode,
	OverseasConsigneeEname,
	DomesticConsigneeEname,
	CorrelationNo,
	EdiRemark2,
	EdiRemark,
	RelId,
	RelManNo,
	BonNo,
	VoyNo,
	DecBpNo,
	CusFie,
	DecNo,
	DecSignOperType,
	DecSignICCode,
	DecSignCopCode,
	DecSignOperName,
	DecSignClientSeqNo,
	DecSign,
	DecSignDate,
	DecSignCertificate,
	DecSignHostId,
	DecSignBillSeqNo,
	DecSignDomainId,
	DecSignNote,
	TrnHeadTrnPreId,
	TrnHeadTransNo,
	TrnHeadTurnNo,
	TrnHeadNativeTrafMode,
	TrnHeadTrafCustomsNo,
	TrnHeadNativeShipName,
	TrnHeadNativeVoyageNo,
	TrnHeadContractorName,
	TrnHeadContractorCode,
	TrnHeadTransFlag,
	TrnHeadValidTime,
	TrnHeadESealFlag,
	TrnHeadNotes,
	TrnHeadTrnType,
	TrnHeadApplCodeScc,
	TrnListTrafMode,
	TrnListShipId,
	TrnListShipNameEn,
	TrnListVoyageNo,
	TrnListBillNo,
	TrnListIEDate,
	TaxFileName,
	TaxSeqNo,
	TaxSddNo,
	TaxIEFlag,
	TaxDeclPort,
	TaxDDate,
	TaxTradeCo,
	TaxTradeName,
	TaxInRatio,
	TaxTradeMode,
	TaxCutMode,
	TaxTransMode,
	TaxFeeMark,
	TaxFeeCurr,
	TaxFeeRate,
	TaxInsurMark,
	TaxInsurCurr,
	TaxInsurRate,
	TaxOtherMark,
	TaxOtherCurr,
	TaxOtherRate,
	TaxManualNo,
	TaxTradeCoScc,
	TaxGrossWt,
	TaxNoteS,
	TaxLegalLiability,
	TaxSign,
	TaxMessId,
	TaxCertSeqNo,
	TaxStatus,
	TaxFDate,
	TaxNO,
	DecRisk,
	DecRiskSign,
	DecRiskSignDate,
	DecRiskNote,	
	DecSeqNo,
	BondInvtNo,
	ChgTmsCnt,
	InvtPreentNo,
	EtpsInnerInvtNo,
	BizopEtpsNo,
	RcvgdEtpsNo,
	DclEtpsNo,
	InvtDclTime,
	EntryDclTime,
	RltInvtNo,
	RltEntryBizopEtpsScCd,
	RltEntryBizopEtpsNo,
	RltEntryBizopEtpsNm,
	MtpckEndprdMarkCd,
	ApplyNo,
	DclcusFlag,
	DclcusTypeCd,
	PrevdTime,
	FormalVrfdedTime,
	InvtIoChkPtStuCd,
	VrfdedMarkCd,
	InvtStuCd,
	VrfdedModeCd,
	DuCode,
	InvtType,
	EntryStuCd,
	PassportUsedTypeCd,
	DclTypeCd,
	LevyBlAmt,
	NeedEntryModified,
	OptStatus,
	CustomName,
	ImpexpCustomName,
	DclPlcCustomName,
	FullTrade,
	TrafSpec,
	RltEntryRvsngdEtpsScCd,
	RltEntryRcvgdEtpsNo,
	RltEntryRcvgdEtpsNm,
	RltEntryDclEtpsScCd,
	RltEntryDclEtpsNo,
	RltEntryDclEtpsNm,
	ListType,
	InputCode,
	InputName,
	InputTime,
	ListStat,
	CorrEntryDclEtpsScCd,
	CorrEntryDclEtpsNo,
	CorrEntryDclEtpsNm,
	DecType,
	Param1,
	Param2,
	Param3,
	Param4,
	DecHeadTradeCiqCode,
	DecHeadOwnerCiqCode,
	DecHeadDeclCiqCode,
	DecRoyaltyFeePricePreDeterminNo,
	DecRoyaltyFeeTaxRoyaltyDeclType,
	DecRoyaltyFeeContractNo,
	DecRoyaltyFeeAuthorizer,
	DecRoyaltyFeeAuthorizedPerson,
	DecRoyaltyFeePayType,
	DecRoyaltyFeePayTime,
	DecRoyaltyFeePayPeriod,
	DecRoyaltyFeeEffectiveDateTime,
	DecRoyaltyFeeExpirationDateTime,
	DecRoyaltyFeeRoyaltyAmount,
	DecRoyaltyFeeCurr,
	DecRoyaltyFeeRoyaltyFeeType,
	DecRoyaltyFeeEdocType,
	DecRoyaltyFeeStatment,
	DecRoyaltyFeeIsSecret,
	DecRoyaltyFeeIsCusAudit,
	DecRoyaltyFeeIsCusPricePreDetermin,
	DecRoyaltyFeeIssueDateTime,
	DecRoyaltyFeePeriodStartDate,
	DecRoyaltyFeePeriodEndDate,
	PutrecNo,
	BizopEtpsSccd,
	BizopEtpsNm,
	EntryNo,
	RltPutrecNo,
	BondInvtTypeCd,
	IcCardNo,
	Rmk,
	CreateFlag,
	ApprovalStatus,
	ApprovalDate,
	DeclarationDate,
	SheetDeclarationTime,
	DeclareTime,
	Ptr8ApprovalDate,
	'''',
	'''',
	'''',
	KeepDuringRollback,
	DeletedFlag 
					
			FROM txdCNDeclarationData TABLOCKX' ) 


			 
				
				
		DECLARE @After_HasData BIT;

		SET @After_HasData=0

		IF (SELECT TOP 1 1 FROM [dbo].[Tmp_txdCNDeclarationData]) = 1 
		BEGIN
			SET @After_HasData=1
		END
		
		IF @Before_HasData = @After_HasData
		BEGIN
			PRINT ''
			PRINT 'APPLYING CHANGES......'
			
			EXEC usp_DBACopyTableIndexes '','txdCNDeclarationData' 
		
			PRINT ''
			PRINT 'DROP TABLE..........'
			DROP TABLE [txdCNDeclarationData] 
		
			PRINT ''
			PRINT 'RENAME TABLE....'
			
			EXECUTE sp_rename N'Tmp_txdCNDeclarationData', N'txdCNDeclarationData', 'OBJECT' 
			
			PRINT ''
			PRINT 'CREATE INDEXES...........'
			
			EXEC usp_DBACreateTableIndexes '','txdCNDeclarationData' 
		END
		ELSE
		BEGIN
			if exists (select TOP 1 1 from sys.tables where Name = 'Tmp_txdCNDeclarationData' 
					AND Type = 'U')
			BEGIN
				PRINT ''
				PRINT 'CHANGES CANNOT BE APPLIED......'
			
				PRINT ''
				PRINT 'DROP TMP TABLE..........'
				DROP TABLE [Tmp_txdCNDeclarationData] 
			END

			PRINT ''
			RAISERROR ('Error:  Changes rolled back to avoid data loss.', 16, 1)
		END
	END
END

