IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tmdABIResponseLookup]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN	
	DECLARE @PartnerID AS INT
	SELECT @PartnerID=  partnerID FROM dbo.tmfDefaults

	IF EXISTS(SELECT * FROM [tmdABIResponseLookup] WHERE MSGIDCode LIKE '%CRSRC%')
	BEGIN
		DELETE FROM tmdABIResponseLookup WHERE MSGIDCode LIKE '%CRSRC%'		
	END
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC11', 'GENERAL', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC12', 'EXAM/SAMPLE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC14', 'DATA REJECTED PER PGA REVIEW', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC15', 'DATA INACCURATE - CONTACT PGA', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC21', 'EXAM DO NOT DEVAN', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC22', 'GENERAL', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC23', 'RELEASED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC24', 'RELEASED WITH COMMENTS', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC25', 'ADDITIONAL VERIFICATION NEEDED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC26', 'PN DATA REJECTED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC28', 'LAB RESULTS PENDING', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC29', 'LAB RESULTS FAILED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC30', 'PN REFUSED PN NOT SUBMITTED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC31', 'PN REG HOLD MANUF NOT RGSTRD', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC34', 'EXAM', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC40', 'REFUSED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC44', 'FAILURE TO PRESENT', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC45', 'FWS CLEARANCE REFUSED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC46', 'PARTIAL RELEASE AND REFUSED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC50', 'FWS CLEARED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC51', 'FWS CONDITIONAL RELEASE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC52', 'PN REFUSED INACCURATE PN', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC53', 'PN REFUSED UNTIMELY PN', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRSRC90', 'ADDITIONAL INFORMATION NEEDED', '', 'N', 'N' )
	
	IF EXISTS(SELECT * FROM [tmdABIResponseLookup] WHERE MSGIDCode LIKE '%CRPGARQ%')
	BEGIN
		DELETE FROM tmdABIResponseLookup WHERE MSGIDCode LIKE '%CRPGARQ%'	
	END

	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ1', 'PRIOR NOTICE CONFIRMATION NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ2', 'PERMIT NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ3', 'AMS CONFIRMATION NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ4', 'AMS FV6 NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ5', 'AMS LPS-222 NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGARQ6', 'FWS EDECS CONFIRMATION NUMBER', '', 'N', 'N' )
	
	IF EXISTS(SELECT * FROM [tmdABIResponseLookup] WHERE MSGIDCode LIKE '%CRPGASR%')
	BEGIN
		DELETE FROM tmdABIResponseLookup WHERE MSGIDCode LIKE '%CRPGASR%'
	END
	
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR100', 'DETAINED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR102', 'REFUSED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR104', 'PGA INSPECTION NEEDED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR105', 'EXAM', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR106', 'EXAM NOTIFY', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR107', 'FOREIGN ULTIMATE CONSIGNEE', '', 'N', 'N' )	
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR113', 'INVALID QUANTITY FORMAT', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR114', 'INVALID ID FOR MANUFACTURER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR115', 'INVALID ID FOR SHIPPER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR116', 'INVALID ID FOR IMPORTER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR117', 'INVALID ID FOR ULTIMATE CONSIGNEE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR118', 'INVALID STATE/ZIP FOR US MANUFATURER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR119', 'INVALID COUNTRY OF PRODUCTION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR120', 'INVALID COUNTRY OF SHIPPING', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR126', 'INVALID FILER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR127', 'INVALID OWNER ENTITY ID', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR128', 'INVALID SUBMITTER ENTITY ID', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR129', 'INVALID TRANSMITTER ENTITY ID', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR130', 'INVALID DELIVER TO PARTY ENTITY ID', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR131', 'MISSING BILL OF LADING OR AIR WAY BILL', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR151', 'MISSING DATA', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR152', 'INVALID CANADIAN PROVINCE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR153', 'INVALID PRODUCTCODE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR154', 'MISSING OR INVALID DATE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR155', 'MISSING, INVALID, OR EXPIRED FWS IMPORT/EXPORT LICENSE NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR156', 'INVALID FWS PORT', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR157', 'INACCURATE FWS INTENDED USE DESCRIPTION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR158', 'MISSING CARRIER NAME', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR159', 'MISSING OR INVALID MODE OF TRANSPORTATION CODE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR160', 'MISSING OR INACCURATE BONDED LOCATION FOR INSPECTION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR161', 'MISSING OR INVALID NUMBER OF CARTONS CONTAINING WILDLIFE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR162', 'MISSING OR INVALID FWS US IMPORTER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR163', 'MISSING OR INVALID FWS FOREIGN EXPORTER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR164', 'MISSING OR INVALID SHIPPING AGENT', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR165', 'MISSING OR INVALID FREIGHT FORWARDER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR166', 'MISSING OR INVALID SCIENTIFIC GENUS NAME', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR167', 'MISSING OR INVALID SCIENTIFIC SPECIES NAME', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR168', 'MISSING OR INVALID SCIENTIFIC SUB SPECIES NAME', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR169', 'MISSING OR INVALID COMMON NAME', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR170', 'MISSING OR INVALID FOREIGN CITES PERMIT NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR171', 'MISSING OR INVALID U.S. CITES PERMIT NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR172', 'MISSING OR INVALID MARKINGS ON CARTONS CONTAINING WILDLIFE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR173', 'MISSING OR INVALID FWS DESCRIPTION CODE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR174', 'MISSING OR INVALID PGA COMMODITY QUALIFIER CODE (FWS SOURCE CODE)', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR175', 'MISSING OR INVALID FWS QUANTITY OR UNIT OF MEASURE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR176', 'FWS CORPORATE ACCOUNT PAYMENT IS OVERDUE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR177', 'MISSING OR INVALID FWS VALUE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR178', 'INVALID FWS COUNTRY OF SPECIES ORIGIN', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR179', 'MISSING OR INVALID VENOMOUS WILDLIFE FLAG', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR183', 'INVALID UNITS OF MEASURE FOR COMMODITY', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR132', 'DOCUMENTATION NEEDED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR108', 'MISSING REGISTRATION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR109', 'REGISTRATION NOT ON FILE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR110', 'MISMATCH IN REGISTRATION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR111', 'CANCELLED MANUFACTURER FACILITY REGISTRATION', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR112', 'MANUFACTURER FACILITY REGISTRATION INVALIDATED BY FDA', '', 'N', 'N' )	
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR122', 'INVALID EXEMPTION(FME) QUALIFIER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR123', 'INVALID PNC NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR124', 'EXPIRED PNC NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR125', 'CANCELLED PNC NUMBER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR149', 'FDA PRODUCT CODE MISMATCH TO GROWER/CONSOLIDATOR/MANUFACTURER ROLE CODE', '', 'N', 'N' )	
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR133', 'INACCURATE MANUFACTURER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR134', 'INACCURATE ULTIMATE CONSIGNEE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR135', 'INACCURATE SHIPPER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR136', 'INACCURATE IMPORTER', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR137', 'INACURRATE FDA PRODUCTCODE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR138', 'INACCURATE BILL OF LADING OR AIRWAY BILL', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR139', 'INACCURATE PRIOR NOTICE- OTHER-CONTACT THE FDA DFDT', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR103', 'PARTIAL RELEASE AND REFUSE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR144', 'REFUSAL SATISFIED', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR145', 'PARTIAL REFUSE', '', 'N', 'N' )
	INSERT INTO dbo.tmdABIResponseLookup VALUES (@PartnerID, Getdate(), 'CRPGASR180', 'DIVERT TO ACCEPTABLE USE', '', 'N', 'N' )
	
END